    --ammo revolver
    ['ammo_revolver']                   = {['name'] = 'ammo_revolver',                   ['label'] = 'Revolver (N)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Revolver Ammo'},
    ['ammo_revolver_express']           = {['name'] = 'ammo_revolver_express',           ['label'] = 'Revolver (E)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_express.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Revolver Express Ammo'},
    ['ammo_revolver_express_explosive'] = {['name'] = 'ammo_revolver_express_explosive', ['label'] = 'Revolver (EE)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_explosive.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Revolver Express Explosive Ammo'},
    ['ammo_revolver_high_velocity']     = {['name'] = 'ammo_revolver_high_velocity',     ['label'] = 'Revolver (HV)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_high_velocity.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Revolver High Velocity Ammo'},
    ['ammo_revolver_split_point']       = {['name'] = 'ammo_revolver_split_point',       ['label'] = 'Revolver (SP)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_split_point.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Revolver Split Point Ammo'},

    -- pistol ammo
    ['ammo_pistol']                   = {['name'] = 'ammo_pistol',                   ['label'] = 'Pistol (N)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Pistol Ammo'},
    ['ammo_pistol_express']           = {['name'] = 'ammo_pistol_express',           ['label'] = 'Pistol (E)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_express.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Pistol Express Ammo'},
    ['ammo_pistol_express_explosive'] = {['name'] = 'ammo_pistol_express_explosive', ['label'] = 'Pistol (EE)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_explosive.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Pistol Express Explosive Ammo'},
    ['ammo_pistol_high_velocity']     = {['name'] = 'ammo_pistol_high_velocity',     ['label'] = 'Pistol (HV)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_high_velocity.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Pistol High Velocity Ammo'},
    ['ammo_pistol_split_point']       = {['name'] = 'ammo_pistol_split_point',       ['label'] = 'Pistol (SP)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_split_point.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Pistol Split Point Ammo'},

    -- repeater ammo
    ['ammo_repeater']                   = {['name'] = 'ammo_repeater',                   ['label'] = 'Repeater (N)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Repeater Ammo'},
    ['ammo_repeater_express']           = {['name'] = 'ammo_repeater_express',           ['label'] = 'Repeater (E)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_express.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Repeater Express Ammo'},
    ['ammo_repeater_express_explosive'] = {['name'] = 'ammo_repeater_express_explosive', ['label'] = 'Repeater (EE)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_explosive.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Repeater Express Explosive Ammo'},
    ['ammo_repeater_high_velocity']     = {['name'] = 'ammo_repeater_high_velocity',     ['label'] = 'Repeater (HV)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_high_velocity.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Repeater High Velocity Ammo'},
    ['ammo_repeater_split_point']       = {['name'] = 'ammo_repeater_split_point',       ['label'] = 'Repeater (SP)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_split_point.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Repeater Split Point Ammo'},

    -- rifle ammo
    ['ammo_rifle']                   = {['name'] = 'ammo_rifle',                   ['label'] = 'Rifle (N)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png',        ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Rifle Ammo'},
    ['ammo_rifle_express']           = {['name'] = 'ammo_rifle_express',           ['label'] = 'Rifle (E)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_express.png',       ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Rifle Express Ammo'},
    ['ammo_rifle_express_explosive'] = {['name'] = 'ammo_rifle_express_explosive', ['label'] = 'Rifle (EE)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_explosive.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Rifle Express Explosive Ammo'},
    ['ammo_rifle_high_velocity']     = {['name'] = 'ammo_rifle_high_velocity',     ['label'] = 'Rifle (HV)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_high_velocity.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Rifle High Velocity Ammo'},
    ['ammo_rifle_split_point']       = {['name'] = 'ammo_rifle_split_point',       ['label'] = 'Rifle (SP)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_split_point.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Rifle Split Point Ammo'},

    --ammo shotgun
    ['ammo_shotgun']                     = {['name'] = 'ammo_shotgun',                     ['label'] = 'Shotgun (N)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_shotgun.png',                     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Shotgun Ammo'},
    ['ammo_shotgun_buckshot_incendiary'] = {['name'] = 'ammo_shotgun_buckshot_incendiary', ['label'] = 'Shotgun (BI)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_shotgun_buckshot_incendiary.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Shotgun Ammo'},
    ['ammo_shotgun_slug']                = {['name'] = 'ammo_shotgun_slug',                ['label'] = 'Shotgun (S)',  ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_shotgun_slug.png',                ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Shotgun Ammo'},
    ['ammo_shotgun_slug_explosive']      = {['name'] = 'ammo_shotgun_slug_explosive',      ['label'] = 'Shotgun (SE)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_shotgun_slug_explosive.png',      ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Shotgun Ammo'},

    -- elephant rifle ammo
    ['ammo_rifle_elephant'] = {['name'] = 'ammo_rifle_elephant', ['label'] = 'Elephant Rifle (N)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Elephant Rifle Ammo'},

    --ammo varmint
    ['ammo_varmint']              = {['name'] = 'ammo_varmint',              ['label'] = 'Varmint (N)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_bullet_normal.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Varmint Ammo'},
    ['ammo_varmint_tranquilizer'] = {['name'] = 'ammo_varmint_tranquilizer', ['label'] = 'Varmint (T)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_22_tranquilizer.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Varmint Ammo'},

    --ammo arrow
    ['ammo_arrow']          = {['name'] = 'ammo_arrow',          ['label'] = 'Arrow (N)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_arrow.png',          ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Arrow'},
    ['ammo_arrow_fire']     = {['name'] = 'ammo_arrow_fire',     ['label'] = 'Arrow (F)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_arrow_fire.png',     ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Arrow'},
    ['ammo_arrow_poison']   = {['name'] = 'ammo_arrow_poison',   ['label'] = 'Arrow (P)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_arrow_poison.png',   ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Arrow'},
    ['ammo_arrow_dynamite'] = {['name'] = 'ammo_arrow_dynamite', ['label'] = 'Arrow (D)', ['weight'] = 200, ['type'] = 'item', ['image'] = 'ammo_arrow_dynamite.png', ['unique'] = false, ['useable'] = true, ['shouldClose'] = true, ['combinable'] = nil, ['level'] = 0, ['description'] = 'Arrow'},
